import type { OxfmtConfig } from 'oxfmt'

const config: OxfmtConfig = {
	arrowParens: 'always',
	ignorePatterns: [
		'*.hbs',
		'pnpm-lock.yaml',
		'node_modules',
		'.pnp',
		'.pnp.*',
		'.yarn/*',
		'!.yarn/patches',
		'!.yarn/plugins',
		'!.yarn/releases',
		'!.yarn/versions',
		'logs',
		'*.log',
		'npm-debug.log*',
		'yarn-debug.log*',
		'yarn-error.log*',
		'pnpm-debug.log*',
		'lerna-debug.log*',
		'.vscode',
		'!.vscode/extensions.json',
		'.idea',
		'.DS_Store',
		'*.suo',
		'*.ntvs*',
		'*.njsproj',
		'*.sln',
		'*.sw?',
		'.tmp',
		'.next',
		'out',
		'next-env.d.ts',
		'build',
		'.DS_Store',
		'*.pem',
		'.env*',
		'.vercel',
		'coverage',
		'node_modules',
		'dist',
		'dist-ssr',
		'*.local',
		'vite.config.ts.timestamp-*',
		'.turbo',
		'*.tsbuildinfo',
		'.gen.',
		'*generated*',
	],
	jsxSingleQuote: true,
	printWidth: 80,
	semi: false,
	singleQuote: true,
	sortPackageJson: false,
	trailingComma: 'all',
	useTabs: true,
}

export default config
