on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches-ignore:
      - main
      - dev
env:
  BASE_PATH: '/funtoyz/'
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Check out code
        uses: actions/checkout@v5
      - name: Cache
        uses: actions/cache@v5
        with:
          path: |
            .turbo
            apps/website/.next/cache
            node_modules/.cache
            .eslintcache
          key: ${{ runner.os }}-cache-${{ github.sha }}
          restore-keys: ${{ runner.os }}-cache-
      - name: Install pnpm
        uses: pnpm/action-setup@v5
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v5
        with:
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Verify
        run: pnpm run verify
      - name: Sherif
        run: pnpm run sherif
      - name: Knip
        run: pnpm run knip
      - name: Upload to Codecov
        if: github.ref == 'refs/heads/main'
        uses: codecov/codecov-action@v5
        with:
          use_oidc: true
          fail_ci_if_error: true
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
