on:
  push:
env:
  BASE_PATH: '/funtoyz/'
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            .turbo
            apps/website/.next/cache
            node_modules/.cache
            .eslintcache
          key: ${{ runner.os }}-cache-${{ github.sha }}
          restore-keys: ${{ runner.os }}-cache-
      - name: Install pnpm
        uses: pnpm/action-setup@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Sherif
        run: pnpm run sherif
      - name: Verify
        run: pnpm run verify
      - name: Knip
        run: pnpm run knip
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
